CREATE TABLE `gift_project`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `BIRTHDATE` DATE NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PHONENUMBER` VARCHAR(45) NULL,
  `GENDER` VARCHAR(45) NULL,
  `PRONOUN` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));
